name: Porto Torto
favicon: null
layout_spectrum: 0.4465342015028
typography_spectrum: 0.7527195373550057
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5051450335886329
  lightness: 0.6735150546301156
  saturation: 0.14686724753119051
  rhythmicContrast: 0.8673856786917895
purpose: []
